spring:
  application:
    name: vkusno-i-prosto
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/vkusno_i_prosto
      database: vkusno_i_prosto
      uuid-representation: java_legacy

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG